amber-lang/heraclitus

- src/compiler/lexer/lexer.rs
- src/compiler/lexer/region_handler.rs
- src/compiler/logger/mod.rs
- src/rules/region.rs
Show error in Lexer if some region was left open
> H6 Feature: Show error on region left open

- Cargo.lock
- Cargo.toml
- src/compiler/compiler.rs
- src/compiler/lexer/region_handler.rs
- src/compiler/logger/displayer.rs
- src/compiler/logger/file_resolution.rs
- src/compiler/logger/logger.rs
- src/compiler/logger/mod.rs
In addition to that it would be good (also for debugging purposes) to show where the error happened (code snippet and an arrow)
> H8 Feature: Make Logger to show the actual messages.

- src/compiler/lexer/lexer.rs
- src/compiler/lexer/region_handler.rs
- src/compiler/logger/logger.rs
Create a way to make _unspillable_ regions. These are the regions that can't be multiline.
> H15 Feature: Add unspillable region option

- src/rules/context.rs
- src/rules/mod.rs
- src/rules/rules.rs
Create context structure that can be used to define contexts like global scope, function scope, class scope etc.
> H11 Feature: Create Contexts

- src/compiler/lexer/lexer.rs
- src/compiler/lexer/region_handler.rs
- src/compiler/logger/displayer.rs
- src/compiler/mod.rs
- src/compiler/parser/mod.rs
- src/compiler/parser/pattern.rs
- src/compiler/parser/preset.rs
- src/compiler/parser/syntax_module.rs
- src/rules/region.rs
Syntax Pattern is an ordered list of Syntax Symbols that can be used to express syntax.
Building blocks of Syntax Pattern:
1. Token
2. Preset
3. Pattern
4. Any
5. Optional
6. Repeat
7. Syntax Module
8. Custom Token
> H18 Feature: Create syntax pattern parser

- src/compiler/parser/pattern.rs
- src/compiler/parser/preset.rs
- src/compiler/parser/syntax_module.rs
Create a metadata object that can be passed to the pattern recognition so that we can pass more data implicitly. This will increase scalability of the project.
> H22 Feature: Add Metadata

- src/compiler/compiler.rs
- src/compiler/lexer/lexer.rs
- src/compiler/logger/displayer.rs
- src/compiler/logger/logger.rs
- src/compiler/parser/mod.rs
- src/compiler/parser/pattern.rs
- src/compiler/parser/preset.rs
- src/compiler/parser/syntax_module.rs
- src/compiler/parser/util.rs
- src/compiler/token.rs
- src/lib.rs
- tests/arith.rs
- tests/cobra.rs
- tests/cobra_modules/block.rs
- tests/cobra_modules/expr.rs
- tests/cobra_modules/if_statement.rs
- tests/cobra_modules/mod.rs
- tests/cobra_modules/text.rs
- tests/lexer.rs
Test parser and check if is good enough.
> H16 Feature: Test Parser

- src/compiler/parser/metadata.rs
- src/compiler/parser/mod.rs
- src/compiler/parser/syntax_module.rs
- tests/arith.rs
- tests/arith_modules/add.rs
- tests/arith_modules/expr.rs
- tests/arith_modules/mod.rs
- tests/arith_modules/number.rs
- Move Metadata to a separate file
- Move Arith submodules to separate files
- Clean up unused variables
> H24 Fix: Clean up code

- tests/arith.rs
- tests/arith_modules/add.rs
- tests/arith_modules/expr.rs
- tests/arith_modules/number.rs
Add a way to express if given pattern is supposed to be read from left to right or from right to left. Build a mechanism that handles it as well.
> H19 Feature: Implement syntax exception for expression

- src/compiler/logger/displayer.rs
- src/compiler/logger/logger.rs
> H37 Feature: Make logger to show simple text messages

- src/compiler/compiler.rs
- src/compiler/parser/metadata.rs
- src/compiler/parser/pattern.rs
- src/compiler/parser/syntax_module.rs
- tests/arith.rs
- tests/arith_modules/add.rs
- tests/arith_modules/expr.rs
- tests/arith_modules/number.rs
- tests/cobra_modules/block.rs
- tests/cobra_modules/expr.rs
- tests/cobra_modules/if_statement.rs
- tests/cobra_modules/text.rs
Create a tool for debugging AST.
> H40 Feature: Syntax Module name method for debugging

- Cargo.lock
- Cargo.toml
- README.md
- src/compiler/logger/error_details.rs
Method that creates error details based on supplied token
> H43 Feature: Create ErrorDetails from token

- README.md
Readme Headers look too small on changelog
> H44 Fix: Fix Readme headers

- src/compiler/lexer/lexer.rs
- src/compiler/lexer/region_handler.rs
If the interpolation has state `tokenize` set to true - this means that it's inner contents shall be separated from the region boundaries.
For instance `'hello {name}'` should parse to:
- ✅  `["hello", "{", "name", "}"]`
- ❌  `["hello", "{name}"]`
> H48 Feature: Fix bad lexer behaviour in interpolation

- src/compiler/compiler.rs
- src/compiler/lexer/lexer.rs
- src/compiler/logger/displayer.rs
- src/compiler/logger/error_details.rs
- src/compiler/logger/logger.rs
- src/compiler/parser/pattern.rs
- src/compiler/parser/preset.rs
Currently displayer highlights just first 3 characters
> H51 Fix: Token highlighting in Displayer

- Cargo.lock
- Cargo.toml
- README.md
- src/compiler/lexer/compound_handler.rs
- src/compiler/lexer/lexer.rs
- src/compiler/logger/logger.rs
- tests/cobra.rs
Sample code:
`# if rubyStatus == 0 downloadRuby(url, target)`
> H52 Fix: Region tokenizing

- Cargo.lock
- Cargo.toml
- src/compiling/compiler.rs
- src/compiling/lexing/lexer.rs
- src/compiling/logging/displayer.rs
- src/compiling/logging/error_details.rs
- src/compiling/logging/logger.rs
- src/compiling/parser/metadata.rs
- src/compiling/parser/pattern.rs
- src/compiling/parser/preset.rs
- tests/arith_modules/add.rs
This pull requests introduces:
- error tracebacks
- logger output to STDERR via `eprintln!`
- color support for macos terminal
> H60-57-58 Feature: Ability to set traceback for erroring, logger outputs to STDERR and colors do not work for macos default terminal

- Cargo.lock
- Cargo.toml
- README.md
- src/compiling/compiler.rs
- src/compiling/failing/failure.rs
- src/compiling/failing/logger.rs
- src/compiling/failing/message.rs
- src/compiling/failing/mod.rs
- src/compiling/failing/position_info.rs
- src/compiling/lexing/lexer.rs
- src/compiling/logging/mod.rs
- src/compiling/mod.rs
- src/compiling/parser/metadata.rs
- src/compiling/parser/mod.rs
- src/compiling/parser/pattern.rs
- src/compiling/parser/preset.rs
- src/compiling/parser/syntax_module.rs
- src/lib.rs
- tests/arith_modules/add.rs
- tests/arith_modules/expr.rs
- tests/cobra_modules/block.rs
Current state of logger results in a messy and confusing interface. The goal of this issue is to clean this up a bit.
> A45 Feature: Create a nice and easy way to utilise logger

- Cargo.lock
- Cargo.toml
- README.md
- src/compiling/failing/message.rs
> Add newline to text errors as well as syntax errors

- src/compiling/failing/position_info.rs
> Fix syntax error position at end of file
